<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('f03m05s', function (Blueprint $table) {
            $table->id();
            $table->text('job_number')->nullable();
            $table->text('product_name')->nullable();
            $table->text('received_date')->nullable();
            $table->text('initiated_date')->nullable();
            $table->text('reported_date')->nullable();
            $table->text('method')->nullable();
            $table->text('unit')->nullable();
            $table->text('pre_enrichment')->nullable();
            $table->text('selective_enrichment')->nullable();
            $table->text('xld1_slant_tsi')->nullable();
            $table->text('xld1_blank_tsi')->nullable();
            $table->text('xld1_butt_tsi')->nullable();
            $table->text('xld1_h2s_tsi')->nullable();
            $table->text('xld1_gas_tsi')->nullable();
            $table->text('xld1_slant_li')->nullable();
            $table->text('xld1_butt_li')->nullable();
            $table->text('xld1_h2s_li')->nullable();
            $table->text('xld1_gas_li')->nullable();
            $table->text('xld2_slant_tsi')->nullable();
            $table->text('xld2_blank_tsi')->nullable();
            $table->text('xld2_butt_tsi')->nullable();
            $table->text('xld2_h2s_tsi')->nullable();
            $table->text('xld2_gas_tsi')->nullable();
            $table->text('xld2_slant_li')->nullable();
            $table->text('xld2_butt_li')->nullable();
            $table->text('xld2_h2s_li')->nullable();
            $table->text('xld2_gas_li')->nullable();
            $table->text('he1_slant_tsi')->nullable();
            $table->text('he1_blank_tsi')->nullable();
            $table->text('he1_butt_tsi')->nullable();
            $table->text('he1_h2s_tsi')->nullable();
            $table->text('he1_gas_tsi')->nullable();
            $table->text('he1_slant_li')->nullable();
            $table->text('he1_butt_li')->nullable();
            $table->text('he1_h2s_li')->nullable();
            $table->text('he1_gas_li')->nullable();
            $table->text('he2_slant_tsi')->nullable();
            $table->text('he2_blank_tsi')->nullable();
            $table->text('he2_butt_tsi')->nullable();
            $table->text('he2_h2s_tsi')->nullable();
            $table->text('he2_gas_tsi')->nullable();
            $table->text('he2_slant_li')->nullable();
            $table->text('he2_butt_li')->nullable();
            $table->text('he2_h2s_li')->nullable();
            $table->text('he2_gas_li')->nullable();
            $table->text('lysine_slant_tsi')->nullable();
            $table->text('lysine_blank_tsi')->nullable();
            $table->text('lysine_butt_tsi')->nullable();
            $table->text('lysine_h2s_tsi')->nullable();
            $table->text('lysine_gas_tsi')->nullable();
            $table->text('lysine_slant_li')->nullable();
            $table->text('lysine_butt_li')->nullable();
            $table->text('lysine_h2s_li')->nullable();
            $table->text('lysine_gas_li')->nullable();
            $table->text('urease_slant_tsi')->nullable();
            $table->text('urease_blank_tsi')->nullable();
            $table->text('urease_butt_tsi')->nullable();
            $table->text('urease_h2s_tsi')->nullable();
            $table->text('urease_gas_tsi')->nullable();
            $table->text('urease_slant_li')->nullable();
            $table->text('urease_butt_li')->nullable();
            $table->text('urease_h2s_li')->nullable();
            $table->text('urease_gas_li')->nullable();
            $table->text('dul_slant_tsi')->nullable();
            $table->text('dul_blank_tsi')->nullable();
            $table->text('dul_butt_tsi')->nullable();
            $table->text('dul_h2s_tsi')->nullable();
            $table->text('dul_gas_tsi')->nullable();
            $table->text('dul_slant_li')->nullable();
            $table->text('dul_butt_li')->nullable();
            $table->text('dul_h2s_li')->nullable();
            $table->text('dul_gas_li')->nullable();
            $table->text('kcn_slant_tsi')->nullable();
            $table->text('kcn_blank_tsi')->nullable();
            $table->text('kcn_butt_tsi')->nullable();
            $table->text('kcn_h2s_tsi')->nullable();
            $table->text('kcn_gas_tsi')->nullable();
            $table->text('kcn_slant_li')->nullable();
            $table->text('kcn_butt_li')->nullable();
            $table->text('kcn_h2s_li')->nullable();
            $table->text('kcn_gas_li')->nullable();
            $table->text('malonate_slant_tsi')->nullable();
            $table->text('malonate_blank_tsi')->nullable();
            $table->text('malonate_butt_tsi')->nullable();
            $table->text('malonate_h2s_tsi')->nullable();
            $table->text('malonate_gas_tsi')->nullable();
            $table->text('malonate_slant_li')->nullable();
            $table->text('malonate_butt_li')->nullable();
            $table->text('malonate_h2s_li')->nullable();
            $table->text('malonate_gas_li')->nullable();
            $table->text('indole_slant_tsi')->nullable();
            $table->text('indole_blank_tsi')->nullable();
            $table->text('indole_butt_tsi')->nullable();
            $table->text('indole_h2s_tsi')->nullable();
            $table->text('indole_gas_tsi')->nullable();
            $table->text('indole_slant_li')->nullable();
            $table->text('indole_butt_li')->nullable();
            $table->text('indole_h2s_li')->nullable();
            $table->text('indole_gas_li')->nullable();
            $table->text('red_slant_tsi')->nullable();
            $table->text('red_blank_tsi')->nullable();
            $table->text('red_butt_tsi')->nullable();
            $table->text('red_h2s_tsi')->nullable();
            $table->text('red_gas_tsi')->nullable();
            $table->text('red_slant_li')->nullable();
            $table->text('red_butt_li')->nullable();
            $table->text('red_h2s_li')->nullable();
            $table->text('red_gas_li')->nullable();
            $table->text('voges_slant_tsi')->nullable();
            $table->text('voges_blank_tsi')->nullable();
            $table->text('voges_butt_tsi')->nullable();
            $table->text('voges_h2s_tsi')->nullable();
            $table->text('voges_gas_tsi')->nullable();
            $table->text('voges_slant_li')->nullable();
            $table->text('voges_butt_li')->nullable();
            $table->text('voges_h2s_li')->nullable();
            $table->text('voges_gas_li')->nullable();
            $table->text('citrate_slant_tsi')->nullable();
            $table->text('citrate_blank_tsi')->nullable();
            $table->text('citrate_butt_tsi')->nullable();
            $table->text('citrate_h2s_tsi')->nullable();
            $table->text('citrate_gas_tsi')->nullable();
            $table->text('citrate_slant_li')->nullable();
            $table->text('citrate_butt_li')->nullable();
            $table->text('citrate_h2s_li')->nullable();
            $table->text('citrate_gas_li')->nullable();
            $table->text('sucrose_slant_tsi')->nullable();
            $table->text('sucrose_blank_tsi')->nullable();
            $table->text('sucrose_butt_tsi')->nullable();
            $table->text('sucrose_h2s_tsi')->nullable();
            $table->text('sucrose_gas_tsi')->nullable();
            $table->text('sucrose_slant_li')->nullable();
            $table->text('sucrose_butt_li')->nullable();
            $table->text('sucrose_h2s_li')->nullable();
            $table->text('sucrose_gas_li')->nullable();
            $table->text('sal')->nullable();
            $table->text('analysed_sign')->nullable();
            $table->text('analysed_date')->nullable();
            $table->text('analysed_name')->nullable();
            $table->text('checked_sign')->nullable();
            $table->text('checked_date')->nullable();
            $table->text('checked_name')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('f03m05s');
    }
};
